[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
optimism = "https://rpc.ankr.com/optimism"
base = "https://rpc.ankr.com/base"
zora = "https://rpc.zora.energy"

pgn = "https://rpc.publicgoods.network"

# TESTNETS
optimism-testnet = "https://optimism-goerli.publicnode.com"
base-testnet = "https://rpc.ankr.com/base_goerli"
zora-tesnet = ""

mode-testnet = "https://sepolia.mode.network"
pgn-testnet = "https://sepolia.publicgoods.network"

[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
