[profile.default]
src = "src"
out = "out"
libs = ["lib"]

bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
optimism = "https://rpc.ankr.com/optimism"
base = "https://rpc.ankr.com/base"
zora = "https://rpc.zora.energy"

pgn = "https://rpc.publicgoods.network"
anvil = "http://127.0.0.1:8545"
zora-testnet = "https://testnet.rpc.zora.co"

# TESTNETS
optimism-goerli = "https://optimism-goerli.publicnode.com"
base-testnet = "https://rpc.ankr.com/base_goerli"
zora-tesnet = ""

mode-testnet = "https://sepolia.mode.network"
pgn-testnet = "https://sepolia.publicgoods.network"

[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}" }
optimism-goerli = { key = "${ETHERSCAN_API_KEY_OPTIMISM}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
